[common]
api_mode=false

;Access token used for performing critical action through Web interface
api_access_token=password

;Default URLs, used when no URL is provided in request, use "|" to separate multiple subscription links, supports local files/URL
default_url=test.ini

;Insert subscription links to requests. Can be used to add node(s) to all exported subscriptions.
enable_insert=true
;URLs to insert to subscription links, use "|" to separate multiple subscription links, supports local files/URL
insert_url=
;Prepend inserted URLs to subscription links. Nodes in insert_url will be added to groups first with non-group-specific match pattern.
prepend_insert_url=true

;Exclude nodes which remarks match the following patterns. Supports regular expression.
exclude_remarks=(到期|剩余流量|时间|官网|产品|平台)

[node_pref]
sort_flag=false
filter_deprecated_nodes=false
append_sub_userinfo=true
clash_use_new_field_name=true

[managed_config]
write_managed_config=true
managed_config_prefix=http://127.0.0.1:25500
config_update_interval=86400
config_update_strict=false

[server]
listen=0.0.0.0
port=25500